image: mcr.microsoft.com/dotnet/core/sdk:5.0



stages:
  - test
  - deploy

release:
  stage: deploy
  only:
    - main
  artifacts:
    paths:
      - publish/
  script:
    # The output path is relative to the position of the csproj-file
    - dotnet publish
    
debug:
  before_script:
   - 'echo | dotnet --version' # must be v 2.2.300 or later for reporter tool to work
   - dotnet tool install dotnet-reportgenerator-globaltool --tool-path tools
  stage: test
  script:
    - dotnet test
  coverage: /Line coverage[\s\S].+%/
  artifacts:
    paths:
      - Reports_Coverage/
    reports:
      junit:
        - '*.Test/TestResults/TestResults.xml'

# takes upwards of 10 minutes, make manual
code_quality:
  stage: test
  when: manual
  image: docker:latest
  variables:
    DOCKER_DRIVER: overlay
  services:
    - docker:dind
  script:
    - docker pull codeclimate/codeclimate
    - docker run 
       --env CODECLIMATE_DEBUG=1 
       --env CODECLIMATE_CODE="$PWD" 
       --volume "$PWD":/code 
       --volume /var/run/docker.sock:/var/run/docker.sock 
       --volume /tmp/cc:/tmp/cc 
       codeclimate/codeclimate analyze -f html > report.html
    #- cat report.html

  artifacts:
    paths: [report.html]
  dependencies: []
  except:
    variables:
      - $CODE_QUALITY_DISABLED